name: flwr-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - flwr[simulation]==1.26.1
    - torch==2.8.0
    - torchvision==0.23.0
    - pandas
    - numpy
    - matplotlib
    - scikit-learn
    - joblib
    - flwr-datasets
    - datasets