name: flower-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip

  - pip:
      - flwr==1.26.1
      - "flwr[simulation]"
      - torch==2.8.0
      - torchvision
      - pandas
      - numpy
      - matplotlib
      - flwr-datasets
      - datasets
      - scikit-learn